#lang sicp

(define (front-ptr deque) (car deque))
(define (rear-ptr deque) (cdr deque))
(define (set-front-ptr! deque item)
  (set-car! deque item))
(define (set-rear-ptr! deque item)
  (set-cdr! deque item))
(define (empty-deque? deque)
  (null? (front-ptr deque)))
(define (make-deque) (cons '() '()))
(define (front-deque deque)
  (if (empty-deque? deque)
      (error "FRONT called with an 
              empty deque" deque)
      (car (front-ptr deque))))
(define (back-deque deque)
  (if (empty-deque? deque)
    (error "BACK called with an empty deque" deque)
    (car (rear-ptr deque))))
(define (print-deque deque)
  (if (empty-deque? deque)
    "EMPTY"
    (front-ptr deque)))
(define (push-back-deque! deque item)
  (let ((new-pair (cons item '())))
    (cond ((empty-deque? deque)
           (set-front-ptr! deque new-pair)
           (set-rear-ptr! deque new-pair)
           (print-deque))
          (else (set-cdr! (rear-ptr deque) 
                          new-pair)
                (set-rear-ptr! deque new-pair)
                (print-deque)))))
(define (push-front-deque! deque item)
  (let ((new-pair (cons item '())))
    (cond ((empty-deque? deque)
           (set-front-ptr! deque new-pair)
           (set-rear-ptr! deque new-pair)
           (print-deque deque))
          (else (set-cdr! (rear-ptr deque)
                          new-pair)
                (set-front-ptr! deque new-pair)
                (print-deque)))))

