#lang sicp

(define (make-account balance pass)
  (let ((count 0))
  (define (withdraw amount)
    (if (>= balance amount)
        (begin
          (set! balance (- balance amount))
          (set! count 0)
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    (set! count 0)
    balance)
  (define (dispatch input-pass m)
    (cond
          ((> count 7) (lambda (_) "CALL THE COPS"))
          ((not (eq? input-pass pass)) (lambda (_) (begin (set! count (+ count 1)) "Incorrect password")))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request:
                 MAKE-ACCOUNT" m))))
  dispatch))
(define (make-joint pp-acc password new-password)
  (lambda (p m)
    (pp-acc (if (eq? p new-password) password #f) m)))

(define peter-acc (make-account 100 'open-sesame))
(define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))
((peter-acc 'rosebud 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((peter-acc 'open-sesame 'withdraw) 10)
((paul-acc 'rosebud 'withdraw) 10)
((peter-acc 'open-sesame 'withdraw) 10)
